trigger:
  branches:
    include: [ main ]
  paths:
    include: [ infra/** ]

pool:
  vmImage: ubuntu-latest

variables:
  - name: ENV
    value: dev                     # will change per branch or pipeline variable
  - name: TF_WORKDIR
    value: infra
  - name: TFVARS
    value: infra/environments/$(ENV).tfvars

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- task: AzureCLI@2
  displayName: 'Terraform Init/Plan/Apply'
  inputs:
    azureSubscription: 'rg-nexgen-platform'       # service connection name
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      cd $(TF_WORKDIR)

      # Backend is pre-configured in backend.tf
      terraform init

      terraform plan -var-file="$(TFVARS)" \
        -var="django_secret=$(DJANGO_SECRET)" \
        -var="sql_admin_pass=$(SQL_ADMIN_PASS)"

      terraform apply -auto-approve -var-file="$(TFVARS)" \
        -var="django_secret=$(DJANGO_SECRET)" \
        -var="sql_admin_pass=$(SQL_ADMIN_PASS)"
  env:
    # For demo simplicity we’ll pass them from pipeline vars once,
    # but in prod will use KV task to fetch them or will use Key Vault references on the app
    DJANGO_SECRET: $(DJANGO_SECRET)
    SQL_ADMIN_PASS: $(SQL_ADMIN_PASS)
